name: cicd

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Shorten commit id
      id: commit
      shell: bash
      run: |
        echo "commit_id=${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        push: true
        tags: vectorrgb/python-app:${{ steps.commit.outputs.commit_id }}
    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Install yq dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv jq

        python3 -m venv "$RUNNER_TEMP/yq-venv"
        "$RUNNER_TEMP/yq-venv/bin/pip" install yq

        echo "$RUNNER_TEMP/yq-venv/bin" >> "$GITHUB_PATH"

    - name: Modify ArgoCD values file
      shell: bash
      env:
        COMMIT_ID: ${{ needs.ci.outputs.commit_id }}
      run: |
        yq -Y --arg tag "$COMMIT_ID" \
          '.image.tag = $tag' \
          charts/python-app/values.yaml > values.yaml.tmp
        mv values.yaml.tmp charts/python-app/values.yaml

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updates values.yaml with commit id ${{ needs.ci.outputs.commit_id }}'

    - name: Install ArgoCD CLI
      shell: bash
      run: |
        curl -k -sSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv ./argocd /usr/local/bin/argocd

    - name: Shorten commit id
      shell: bash
      run: |
        argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}
        argocd app sync python-app